# Generated by Django 3.2.16 on 2022-10-16 19:00

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.Pet', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
