# Generated by Django 3.2.16 on 2022-11-26 20:36

import cloudinary.models
from django.db import migrations
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
